import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { Platform } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import { getLocales } from 'expo-localization';

export type LocaleCode = 'en'|'he'|'ar'|'es'|'fr'|'de'|'it'|'pt'|'tr'|'hi'|'ja'|'ko';

export const localeOptions: Array<{code:LocaleCode; name:string; flag:string; rtl?:boolean}> = [
  {code:'en',name:'English',flag:'🇬🇧'}, {code:'he',name:'עברית',flag:'🇮🇱',rtl:true}, {code:'ar',name:'العربية',flag:'🇦🇪',rtl:true},
  {code:'es',name:'Español',flag:'🇪🇸'}, {code:'fr',name:'Français',flag:'🇫🇷'}, {code:'de',name:'Deutsch',flag:'🇩🇪'},
  {code:'it',name:'Italiano',flag:'🇮🇹'}, {code:'pt',name:'Português',flag:'🇧🇷'}, {code:'tr',name:'Türkçe',flag:'🇹🇷'},
  {code:'hi',name:'हिन्दी',flag:'🇮🇳'}, {code:'ja',name:'日本語',flag:'🇯🇵'}, {code:'ko',name:'한국어',flag:'🇰🇷'},
];

const en = {
  tagline:'Family safety. Always connected.', welcomeKicker:'Family safety, reimagined', welcomeTitle:'Stay close without feeling intrusive.',
  welcomeSubtitle:'Private family location, SOS, Safe Places and transparent Safety Audio — built around consent and clear controls.',
  parentRole:'I’m a parent / guardian', parentRoleSub:'Create and manage your private family circle.', joinRole:'I’m joining my family', joinRoleSub:'Enter the 6-digit code from your parent or guardian.',
  createFamily:'Create family', signIn:'Sign in', exploreDemo:'Explore interactive demo', privacyFirst:'Privacy-first', privacyFirstSub:'Only approved family members can access your circle.',
  transparent:'Transparent monitoring', transparentSub:'Location and microphone activity are never hidden from the family-member device.', global:'Built for the world', globalSub:'12 launch languages with RTL support for Hebrew and Arabic.',
  selectLanguage:'Select language', languageSubtitle:'Choose your preferred language. You can change it anytime.', parentAccount:'Parent account', createCircle:'Create your family circle', createCircleSub:'Your family is private by default. Only people you invite can join.',
  yourName:'Your name', familyName:'Family name', email:'Email', password:'Password', passwordMin:'At least 10 characters', createNewFamily:'Create a new family', welcomeBack:'Welcome back', signinTitle:'Sign in to your family', signinSub:'Your family circle stays private and encrypted in transit.',
  joinSetup:'Family member setup', joinTitle:'Join your private family circle', joinSub:'Your parent or guardian gives you the 6-digit code. Pairing never hides monitoring or bypasses phone privacy controls.', inviteCode:'Invite code', memberName:'Your name', joinFamily:'Join family',
  locationChoice:'Location is your choice', locationChoiceSub:'AGAM asks before location sharing starts and keeps required system indicators visible.', audioVisible:'Safety Audio is visible', audioVisibleSub:'A microphone session is never hidden from the family-member device.',
  addMember:'Add a family member', pairTitle:'Pair in under a minute', pairSub:'Open AGAM Family on the other device and scan this QR or type the 6-digit code.', generateCode:'Generate a new code', openDashboard:'Open family dashboard', testJoin:'Test the family-member join flow on this device', privateInvite:'PRIVATE INVITE • EXPIRES IN 10 MINUTES', previewCode:'PREVIEW CODE • CLOUD NOT CONNECTED YET', expiresIn:'Expires',
};
export type TranslationKey = keyof typeof en;
type Dictionary = Record<TranslationKey,string>;

const resources: Record<LocaleCode, Dictionary> = {
  en,
  he:{tagline:'בטיחות למשפחה. תמיד מחוברים.',welcomeKicker:'בטיחות משפחתית, מחדש',welcomeTitle:'להישאר קרובים בלי להרגיש פולשני.',welcomeSubtitle:'מיקום משפחתי פרטי, SOS, אזורים בטוחים ושמע בטיחותי שקוף — עם הסכמה ושליטה ברורה.',parentRole:'אני הורה / אפוטרופוס',parentRoleSub:'יצירה וניהול של המעגל המשפחתי הפרטי שלך.',joinRole:'אני מצטרף למשפחה שלי',joinRoleSub:'הזינו את הקוד בן 6 הספרות שקיבלתם מהורה או אפוטרופוס.',createFamily:'יצירת משפחה',signIn:'כניסה',exploreDemo:'צפייה בדמו אינטראקטיבי',privacyFirst:'פרטיות לפני הכול',privacyFirstSub:'רק בני משפחה שאושרו יכולים לגשת למעגל שלך.',transparent:'ניטור שקוף',transparentSub:'פעילות מיקום ומיקרופון לעולם אינה מוסתרת מהמכשיר של בן המשפחה.',global:'נבנה לעולם כולו',globalSub:'12 שפות בהשקה עם תמיכה מלאה מימין לשמאל בעברית ובערבית.',selectLanguage:'בחירת שפה',languageSubtitle:'בחרו את השפה המועדפת. אפשר לשנות אותה בכל עת.',parentAccount:'חשבון הורה',createCircle:'יצירת המעגל המשפחתי שלך',createCircleSub:'המשפחה פרטית כברירת מחדל. רק מי שתזמינו יוכל להצטרף.',yourName:'השם שלך',familyName:'שם המשפחה',email:'אימייל',password:'סיסמה',passwordMin:'לפחות 10 תווים',createNewFamily:'יצירת משפחה חדשה',welcomeBack:'ברוכים השבים',signinTitle:'כניסה למשפחה שלך',signinSub:'המעגל המשפחתי נשאר פרטי ומוצפן בתעבורה.',joinSetup:'הגדרת בן משפחה',joinTitle:'הצטרפות למעגל המשפחתי הפרטי',joinSub:'הורה או אפוטרופוס נותן לכם קוד בן 6 ספרות. הצימוד אינו מסתיר ניטור ואינו עוקף את הגדרות הפרטיות בטלפון.',inviteCode:'קוד הזמנה',memberName:'השם שלך',joinFamily:'הצטרפות למשפחה',locationChoice:'המיקום בשליטתך',locationChoiceSub:'AGAM מבקשת אישור לפני שיתוף מיקום ומשאירה את חיווי המערכת הנדרש גלוי.',audioVisible:'שמע בטיחותי גלוי',audioVisibleSub:'הפעלת המיקרופון לעולם אינה מוסתרת מהמכשיר של בן המשפחה.',addMember:'הוספת בן משפחה',pairTitle:'צימוד בפחות מדקה',pairSub:'פתחו את AGAM Family במכשיר השני וסרקו את ה־QR או הזינו את הקוד בן 6 הספרות.',generateCode:'יצירת קוד חדש',openDashboard:'פתיחת לוח המשפחה',testJoin:'בדיקת תהליך ההצטרפות במכשיר הזה',privateInvite:'הזמנה פרטית • תוקף 10 דקות',previewCode:'קוד דמו • הענן עדיין לא מחובר',expiresIn:'בתוקף עד'},
  ar:{tagline:'أمان العائلة. اتصال دائم.',welcomeKicker:'أمان عائلي بتجربة جديدة',welcomeTitle:'ابقوا قريبين من دون شعور بالتطفل.',welcomeSubtitle:'موقع عائلي خاص وSOS وأماكن آمنة وصوت أمان شفاف — مبني على الموافقة والتحكم الواضح.',parentRole:'أنا والد / ولي أمر',parentRoleSub:'أنشئ وأدر دائرتك العائلية الخاصة.',joinRole:'أنضم إلى عائلتي',joinRoleSub:'أدخل الرمز المكوّن من 6 أرقام من الوالد أو ولي الأمر.',createFamily:'إنشاء عائلة',signIn:'تسجيل الدخول',exploreDemo:'استكشاف العرض التفاعلي',privacyFirst:'الخصوصية أولاً',privacyFirstSub:'فقط أفراد العائلة المعتمدون يمكنهم الوصول إلى دائرتك.',transparent:'مراقبة شفافة',transparentSub:'لا يتم إخفاء نشاط الموقع أو الميكروفون عن جهاز فرد العائلة.',global:'مصمم للعالم',globalSub:'12 لغة عند الإطلاق مع دعم RTL للعربية والعبرية.',selectLanguage:'اختر اللغة',languageSubtitle:'اختر لغتك المفضلة ويمكنك تغييرها في أي وقت.',parentAccount:'حساب الوالد',createCircle:'أنشئ دائرتك العائلية',createCircleSub:'عائلتك خاصة افتراضياً، ولا ينضم إلا من تدعوه.',yourName:'اسمك',familyName:'اسم العائلة',email:'البريد الإلكتروني',password:'كلمة المرور',passwordMin:'10 أحرف على الأقل',createNewFamily:'إنشاء عائلة جديدة',welcomeBack:'مرحباً بعودتك',signinTitle:'سجّل الدخول إلى عائلتك',signinSub:'تبقى دائرتك العائلية خاصة ومشفرة أثناء النقل.',joinSetup:'إعداد فرد العائلة',joinTitle:'انضم إلى دائرتك العائلية الخاصة',joinSub:'يعطيك الوالد أو ولي الأمر رمزاً من 6 أرقام. الاقتران لا يخفي المراقبة ولا يتجاوز إعدادات خصوصية الهاتف.',inviteCode:'رمز الدعوة',memberName:'اسمك',joinFamily:'الانضمام للعائلة',locationChoice:'الموقع باختيارك',locationChoiceSub:'تطلب AGAM الإذن قبل مشاركة الموقع وتبقي مؤشرات النظام المطلوبة ظاهرة.',audioVisible:'صوت الأمان ظاهر',audioVisibleSub:'جلسة الميكروفون لا تُخفى أبداً عن جهاز فرد العائلة.',addMember:'إضافة فرد من العائلة',pairTitle:'الاقتران خلال أقل من دقيقة',pairSub:'افتح AGAM Family على الجهاز الآخر وامسح QR أو أدخل الرمز المكوّن من 6 أرقام.',generateCode:'إنشاء رمز جديد',openDashboard:'فتح لوحة العائلة',testJoin:'اختبار مسار الانضمام على هذا الجهاز',privateInvite:'دعوة خاصة • تنتهي خلال 10 دقائق',previewCode:'رمز تجريبي • السحابة غير متصلة بعد',expiresIn:'ينتهي'},
  es:{tagline:'Seguridad familiar. Siempre conectados.',welcomeKicker:'Seguridad familiar, reinventada',welcomeTitle:'Mantente cerca sin sentirte invasivo.',welcomeSubtitle:'Ubicación familiar privada, SOS, Lugares Seguros y Audio de Seguridad transparente, con consentimiento y controles claros.',parentRole:'Soy padre / tutor',parentRoleSub:'Crea y gestiona tu círculo familiar privado.',joinRole:'Me uno a mi familia',joinRoleSub:'Introduce el código de 6 dígitos de tu padre o tutor.',createFamily:'Crear familia',signIn:'Iniciar sesión',exploreDemo:'Explorar demo interactiva',privacyFirst:'Privacidad primero',privacyFirstSub:'Solo los familiares aprobados pueden acceder a tu círculo.',transparent:'Supervisión transparente',transparentSub:'La actividad de ubicación y micrófono nunca se oculta en el dispositivo familiar.',global:'Hecho para el mundo',globalSub:'12 idiomas de lanzamiento con RTL para hebreo y árabe.',selectLanguage:'Seleccionar idioma',languageSubtitle:'Elige tu idioma preferido. Puedes cambiarlo cuando quieras.',parentAccount:'Cuenta de padre',createCircle:'Crea tu círculo familiar',createCircleSub:'Tu familia es privada por defecto. Solo se unen las personas que invites.',yourName:'Tu nombre',familyName:'Nombre de la familia',email:'Correo electrónico',password:'Contraseña',passwordMin:'Al menos 10 caracteres',createNewFamily:'Crear una nueva familia',welcomeBack:'Bienvenido de nuevo',signinTitle:'Entra en tu familia',signinSub:'Tu círculo familiar permanece privado y cifrado en tránsito.',joinSetup:'Configuración de familiar',joinTitle:'Únete a tu círculo familiar privado',joinSub:'Tu padre o tutor te da el código de 6 dígitos. El emparejamiento no oculta la supervisión ni evita los controles de privacidad.',inviteCode:'Código de invitación',memberName:'Tu nombre',joinFamily:'Unirse a la familia',locationChoice:'La ubicación es tu elección',locationChoiceSub:'AGAM pide permiso antes de compartir ubicación y mantiene visibles los indicadores del sistema.',audioVisible:'El Audio de Seguridad es visible',audioVisibleSub:'Una sesión de micrófono nunca se oculta en el dispositivo familiar.',addMember:'Añadir familiar',pairTitle:'Empareja en menos de un minuto',pairSub:'Abre AGAM Family en el otro dispositivo y escanea el QR o escribe el código de 6 dígitos.',generateCode:'Generar nuevo código',openDashboard:'Abrir panel familiar',testJoin:'Probar el flujo de unión en este dispositivo',privateInvite:'INVITACIÓN PRIVADA • CADUCA EN 10 MINUTOS',previewCode:'CÓDIGO DEMO • NUBE AÚN NO CONECTADA',expiresIn:'Caduca'},
  fr:{tagline:'Sécurité familiale. Toujours connectés.',welcomeKicker:'La sécurité familiale réinventée',welcomeTitle:'Restez proches sans être intrusifs.',welcomeSubtitle:'Localisation privée, SOS, Lieux sûrs et Audio Sécurité transparent — avec consentement et contrôles clairs.',parentRole:'Je suis parent / tuteur',parentRoleSub:'Créez et gérez votre cercle familial privé.',joinRole:'Je rejoins ma famille',joinRoleSub:'Saisissez le code à 6 chiffres donné par votre parent ou tuteur.',createFamily:'Créer la famille',signIn:'Se connecter',exploreDemo:'Explorer la démo interactive',privacyFirst:'Confidentialité d’abord',privacyFirstSub:'Seuls les membres approuvés peuvent accéder à votre cercle.',transparent:'Suivi transparent',transparentSub:'L’activité de localisation et du micro n’est jamais cachée sur l’appareil du membre.',global:'Conçu pour le monde',globalSub:'12 langues au lancement, avec RTL pour l’hébreu et l’arabe.',selectLanguage:'Choisir la langue',languageSubtitle:'Choisissez votre langue. Vous pourrez la modifier à tout moment.',parentAccount:'Compte parent',createCircle:'Créez votre cercle familial',createCircleSub:'Votre famille est privée par défaut. Seules les personnes invitées peuvent rejoindre.',yourName:'Votre nom',familyName:'Nom de la famille',email:'E-mail',password:'Mot de passe',passwordMin:'Au moins 10 caractères',createNewFamily:'Créer une nouvelle famille',welcomeBack:'Bon retour',signinTitle:'Connectez-vous à votre famille',signinSub:'Votre cercle familial reste privé et chiffré pendant le transport.',joinSetup:'Configuration du membre',joinTitle:'Rejoignez votre cercle familial privé',joinSub:'Votre parent ou tuteur vous donne un code à 6 chiffres. L’appairage ne masque jamais le suivi et ne contourne pas les contrôles de confidentialité.',inviteCode:'Code d’invitation',memberName:'Votre nom',joinFamily:'Rejoindre la famille',locationChoice:'La localisation reste votre choix',locationChoiceSub:'AGAM demande l’autorisation avant le partage et conserve les indicateurs système requis visibles.',audioVisible:'Audio Sécurité visible',audioVisibleSub:'Une session micro n’est jamais cachée sur l’appareil du membre.',addMember:'Ajouter un membre',pairTitle:'Appairez en moins d’une minute',pairSub:'Ouvrez AGAM Family sur l’autre appareil puis scannez le QR ou saisissez le code à 6 chiffres.',generateCode:'Générer un nouveau code',openDashboard:'Ouvrir le tableau familial',testJoin:'Tester le parcours membre sur cet appareil',privateInvite:'INVITATION PRIVÉE • EXPIRE DANS 10 MINUTES',previewCode:'CODE DÉMO • CLOUD PAS ENCORE CONNECTÉ',expiresIn:'Expire'},
  de:{tagline:'Familiensicherheit. Immer verbunden.',welcomeKicker:'Familiensicherheit neu gedacht',welcomeTitle:'Nah bleiben, ohne aufdringlich zu sein.',welcomeSubtitle:'Private Familienortung, SOS, sichere Orte und transparentes Safety Audio — mit Zustimmung und klarer Kontrolle.',parentRole:'Ich bin Elternteil / Erziehungsberechtigter',parentRoleSub:'Erstelle und verwalte deinen privaten Familienkreis.',joinRole:'Ich trete meiner Familie bei',joinRoleSub:'Gib den 6-stelligen Code deiner Eltern oder Betreuungsperson ein.',createFamily:'Familie erstellen',signIn:'Anmelden',exploreDemo:'Interaktive Demo ansehen',privacyFirst:'Datenschutz zuerst',privacyFirstSub:'Nur freigegebene Familienmitglieder haben Zugriff.',transparent:'Transparente Überwachung',transparentSub:'Standort- und Mikrofonaktivität wird auf dem Familiengerät nie verborgen.',global:'Für die Welt entwickelt',globalSub:'12 Startsprachen mit RTL-Unterstützung für Hebräisch und Arabisch.',selectLanguage:'Sprache wählen',languageSubtitle:'Wähle deine bevorzugte Sprache. Du kannst sie jederzeit ändern.',parentAccount:'Elternkonto',createCircle:'Erstelle deinen Familienkreis',createCircleSub:'Deine Familie ist standardmäßig privat. Nur eingeladene Personen können beitreten.',yourName:'Dein Name',familyName:'Familienname',email:'E-Mail',password:'Passwort',passwordMin:'Mindestens 10 Zeichen',createNewFamily:'Neue Familie erstellen',welcomeBack:'Willkommen zurück',signinTitle:'Bei deiner Familie anmelden',signinSub:'Dein Familienkreis bleibt privat und bei der Übertragung verschlüsselt.',joinSetup:'Familienmitglied einrichten',joinTitle:'Tritt deinem privaten Familienkreis bei',joinSub:'Deine Eltern oder Betreuungsperson geben dir einen 6-stelligen Code. Die Kopplung verbirgt keine Überwachung und umgeht keine Datenschutzkontrollen.',inviteCode:'Einladungscode',memberName:'Dein Name',joinFamily:'Familie beitreten',locationChoice:'Standort bleibt deine Wahl',locationChoiceSub:'AGAM fragt vor der Standortfreigabe und lässt erforderliche Systemanzeigen sichtbar.',audioVisible:'Safety Audio ist sichtbar',audioVisibleSub:'Eine Mikrofonsitzung wird auf dem Familiengerät nie verborgen.',addMember:'Familienmitglied hinzufügen',pairTitle:'In unter einer Minute koppeln',pairSub:'Öffne AGAM Family auf dem anderen Gerät und scanne den QR-Code oder gib den 6-stelligen Code ein.',generateCode:'Neuen Code erstellen',openDashboard:'Familien-Dashboard öffnen',testJoin:'Beitritt auf diesem Gerät testen',privateInvite:'PRIVATE EINLADUNG • 10 MINUTEN GÜLTIG',previewCode:'DEMO-CODE • CLOUD NOCH NICHT VERBUNDEN',expiresIn:'Gültig bis'},
  it:{tagline:'Sicurezza familiare. Sempre connessi.',welcomeKicker:'Sicurezza familiare, reinventata',welcomeTitle:'Resta vicino senza essere invadente.',welcomeSubtitle:'Posizione familiare privata, SOS, Luoghi Sicuri e Audio Sicurezza trasparente — con consenso e controlli chiari.',parentRole:'Sono genitore / tutore',parentRoleSub:'Crea e gestisci il tuo cerchio familiare privato.',joinRole:'Sto entrando nella mia famiglia',joinRoleSub:'Inserisci il codice a 6 cifre del genitore o tutore.',createFamily:'Crea famiglia',signIn:'Accedi',exploreDemo:'Esplora la demo interattiva',privacyFirst:'Privacy prima di tutto',privacyFirstSub:'Solo i familiari approvati possono accedere al cerchio.',transparent:'Monitoraggio trasparente',transparentSub:'Posizione e microfono non vengono mai nascosti sul dispositivo del familiare.',global:'Pensato per il mondo',globalSub:'12 lingue al lancio con RTL per ebraico e arabo.',selectLanguage:'Seleziona lingua',languageSubtitle:'Scegli la lingua preferita. Puoi cambiarla in qualsiasi momento.',parentAccount:'Account genitore',createCircle:'Crea il tuo cerchio familiare',createCircleSub:'La famiglia è privata per impostazione predefinita. Entrano solo le persone invitate.',yourName:'Il tuo nome',familyName:'Nome famiglia',email:'Email',password:'Password',passwordMin:'Almeno 10 caratteri',createNewFamily:'Crea una nuova famiglia',welcomeBack:'Bentornato',signinTitle:'Accedi alla tua famiglia',signinSub:'Il tuo cerchio resta privato e cifrato durante il trasferimento.',joinSetup:'Configurazione familiare',joinTitle:'Entra nel tuo cerchio familiare privato',joinSub:'Il genitore o tutore ti dà un codice a 6 cifre. L’abbinamento non nasconde il monitoraggio e non aggira i controlli privacy.',inviteCode:'Codice invito',memberName:'Il tuo nome',joinFamily:'Entra nella famiglia',locationChoice:'La posizione è una tua scelta',locationChoiceSub:'AGAM chiede il permesso prima di condividere la posizione e mantiene visibili gli indicatori di sistema.',audioVisible:'Audio Sicurezza visibile',audioVisibleSub:'Una sessione microfono non viene mai nascosta sul dispositivo del familiare.',addMember:'Aggiungi familiare',pairTitle:'Abbina in meno di un minuto',pairSub:'Apri AGAM Family sull’altro dispositivo e scansiona il QR o inserisci il codice a 6 cifre.',generateCode:'Genera nuovo codice',openDashboard:'Apri dashboard famiglia',testJoin:'Prova il flusso di ingresso su questo dispositivo',privateInvite:'INVITO PRIVATO • SCADE TRA 10 MINUTI',previewCode:'CODICE DEMO • CLOUD NON ANCORA CONNESSO',expiresIn:'Scade'},
  pt:{tagline:'Segurança familiar. Sempre conectados.',welcomeKicker:'Segurança familiar reinventada',welcomeTitle:'Fiquem perto sem parecer invasivo.',welcomeSubtitle:'Localização familiar privada, SOS, Lugares Seguros e Áudio de Segurança transparente — com consentimento e controles claros.',parentRole:'Sou pai/mãe / responsável',parentRoleSub:'Crie e gerencie seu círculo familiar privado.',joinRole:'Estou entrando na minha família',joinRoleSub:'Digite o código de 6 dígitos do seu responsável.',createFamily:'Criar família',signIn:'Entrar',exploreDemo:'Explorar demo interativa',privacyFirst:'Privacidade primeiro',privacyFirstSub:'Somente familiares aprovados podem acessar seu círculo.',transparent:'Monitoramento transparente',transparentSub:'Localização e microfone nunca ficam ocultos no dispositivo do familiar.',global:'Feito para o mundo',globalSub:'12 idiomas no lançamento com RTL para hebraico e árabe.',selectLanguage:'Selecionar idioma',languageSubtitle:'Escolha seu idioma. Você pode alterá-lo a qualquer momento.',parentAccount:'Conta do responsável',createCircle:'Crie seu círculo familiar',createCircleSub:'Sua família é privada por padrão. Só entra quem você convidar.',yourName:'Seu nome',familyName:'Nome da família',email:'E-mail',password:'Senha',passwordMin:'Pelo menos 10 caracteres',createNewFamily:'Criar nova família',welcomeBack:'Bem-vindo de volta',signinTitle:'Entre na sua família',signinSub:'Seu círculo permanece privado e criptografado em trânsito.',joinSetup:'Configuração do familiar',joinTitle:'Entre no seu círculo familiar privado',joinSub:'Seu responsável fornece um código de 6 dígitos. O pareamento não oculta o monitoramento nem ignora controles de privacidade.',inviteCode:'Código de convite',memberName:'Seu nome',joinFamily:'Entrar na família',locationChoice:'A localização é sua escolha',locationChoiceSub:'AGAM pede permissão antes de compartilhar e mantém visíveis os indicadores exigidos pelo sistema.',audioVisible:'Áudio de Segurança visível',audioVisibleSub:'Uma sessão de microfone nunca fica escondida no dispositivo do familiar.',addMember:'Adicionar familiar',pairTitle:'Pareie em menos de um minuto',pairSub:'Abra AGAM Family no outro dispositivo e escaneie o QR ou digite o código de 6 dígitos.',generateCode:'Gerar novo código',openDashboard:'Abrir painel da família',testJoin:'Testar entrada neste dispositivo',privateInvite:'CONVITE PRIVADO • EXPIRA EM 10 MINUTOS',previewCode:'CÓDIGO DEMO • NUVEM AINDA NÃO CONECTADA',expiresIn:'Expira'},
  tr:{tagline:'Aile güvenliği. Her zaman bağlı.',welcomeKicker:'Aile güvenliği yeniden tasarlandı',welcomeTitle:'Müdahaleci hissettirmeden yakın kalın.',welcomeSubtitle:'Özel aile konumu, SOS, Güvenli Yerler ve şeffaf Güvenlik Sesi — onay ve açık kontrollerle.',parentRole:'Ebeveyn / vasiyim',parentRoleSub:'Özel aile çevrenizi oluşturun ve yönetin.',joinRole:'Aileme katılıyorum',joinRoleSub:'Ebeveyninizden veya vasinizden aldığınız 6 haneli kodu girin.',createFamily:'Aile oluştur',signIn:'Giriş yap',exploreDemo:'Etkileşimli demoyu keşfet',privacyFirst:'Önce gizlilik',privacyFirstSub:'Çevrenize yalnızca onaylı aile üyeleri erişebilir.',transparent:'Şeffaf izleme',transparentSub:'Konum ve mikrofon etkinliği aile üyesinin cihazında asla gizlenmez.',global:'Dünya için tasarlandı',globalSub:'İbranice ve Arapça RTL desteğiyle 12 lansman dili.',selectLanguage:'Dil seç',languageSubtitle:'Tercih ettiğiniz dili seçin. İstediğiniz zaman değiştirebilirsiniz.',parentAccount:'Ebeveyn hesabı',createCircle:'Aile çevrenizi oluşturun',createCircleSub:'Aileniz varsayılan olarak özeldir. Yalnızca davet ettikleriniz katılabilir.',yourName:'Adınız',familyName:'Aile adı',email:'E-posta',password:'Şifre',passwordMin:'En az 10 karakter',createNewFamily:'Yeni aile oluştur',welcomeBack:'Tekrar hoş geldiniz',signinTitle:'Ailenize giriş yapın',signinSub:'Aile çevreniz özel kalır ve aktarım sırasında şifrelenir.',joinSetup:'Aile üyesi kurulumu',joinTitle:'Özel aile çevrenize katılın',joinSub:'Ebeveyn veya vasi size 6 haneli kod verir. Eşleştirme izlemeyi gizlemez ve telefonun gizlilik kontrollerini aşmaz.',inviteCode:'Davet kodu',memberName:'Adınız',joinFamily:'Aileye katıl',locationChoice:'Konum sizin seçiminiz',locationChoiceSub:'AGAM konum paylaşımından önce izin ister ve gerekli sistem göstergelerini görünür tutar.',audioVisible:'Güvenlik Sesi görünür',audioVisibleSub:'Mikrofon oturumu aile üyesinin cihazında asla gizlenmez.',addMember:'Aile üyesi ekle',pairTitle:'Bir dakikadan kısa sürede eşleştirin',pairSub:'Diğer cihazda AGAM Family’yi açın ve QR kodunu tarayın veya 6 haneli kodu girin.',generateCode:'Yeni kod oluştur',openDashboard:'Aile panelini aç',testJoin:'Bu cihazda katılım akışını test et',privateInvite:'ÖZEL DAVET • 10 DAKİKADA SONA ERER',previewCode:'DEMO KODU • BULUT HENÜZ BAĞLI DEĞİL',expiresIn:'Bitiş'},
  hi:{tagline:'परिवार की सुरक्षा। हमेशा जुड़े रहें।',welcomeKicker:'परिवार सुरक्षा का नया रूप',welcomeTitle:'बिना दखल जैसा महसूस कराए करीब रहें।',welcomeSubtitle:'निजी पारिवारिक लोकेशन, SOS, सुरक्षित स्थान और पारदर्शी सेफ्टी ऑडियो — सहमति और स्पष्ट नियंत्रण के साथ।',parentRole:'मैं माता-पिता / अभिभावक हूँ',parentRoleSub:'अपना निजी परिवार सर्कल बनाएं और प्रबंधित करें।',joinRole:'मैं अपने परिवार से जुड़ रहा/रही हूँ',joinRoleSub:'माता-पिता या अभिभावक से मिला 6 अंकों का कोड डालें।',createFamily:'परिवार बनाएं',signIn:'साइन इन',exploreDemo:'इंटरैक्टिव डेमो देखें',privacyFirst:'गोपनीयता पहले',privacyFirstSub:'केवल स्वीकृत परिवार सदस्य आपके सर्कल तक पहुँच सकते हैं।',transparent:'पारदर्शी निगरानी',transparentSub:'लोकेशन और माइक्रोफोन गतिविधि परिवार सदस्य के डिवाइस पर कभी छिपी नहीं रहती।',global:'दुनिया के लिए बनाया गया',globalSub:'हिब्रू और अरबी RTL सहित 12 लॉन्च भाषाएँ।',selectLanguage:'भाषा चुनें',languageSubtitle:'अपनी पसंदीदा भाषा चुनें। इसे कभी भी बदल सकते हैं।',parentAccount:'अभिभावक खाता',createCircle:'अपना परिवार सर्कल बनाएं',createCircleSub:'आपका परिवार डिफ़ॉल्ट रूप से निजी है। केवल आमंत्रित लोग जुड़ सकते हैं।',yourName:'आपका नाम',familyName:'परिवार का नाम',email:'ईमेल',password:'पासवर्ड',passwordMin:'कम से कम 10 अक्षर',createNewFamily:'नया परिवार बनाएं',welcomeBack:'वापसी पर स्वागत है',signinTitle:'अपने परिवार में साइन इन करें',signinSub:'आपका परिवार सर्कल निजी रहता है और ट्रांज़िट में एन्क्रिप्टेड है।',joinSetup:'परिवार सदस्य सेटअप',joinTitle:'अपने निजी परिवार सर्कल से जुड़ें',joinSub:'माता-पिता या अभिभावक 6 अंकों का कोड देते हैं। पेयरिंग निगरानी नहीं छिपाती और फोन की गोपनीयता सेटिंग्स को बायपास नहीं करती।',inviteCode:'आमंत्रण कोड',memberName:'आपका नाम',joinFamily:'परिवार से जुड़ें',locationChoice:'लोकेशन आपकी पसंद है',locationChoiceSub:'AGAM लोकेशन साझा करने से पहले अनुमति मांगता है और आवश्यक सिस्टम संकेतक दिखाता है।',audioVisible:'सेफ्टी ऑडियो दिखाई देता है',audioVisibleSub:'माइक्रोफोन सत्र परिवार सदस्य के डिवाइस पर कभी छिपाया नहीं जाता।',addMember:'परिवार सदस्य जोड़ें',pairTitle:'एक मिनट से कम में पेयर करें',pairSub:'दूसरे डिवाइस पर AGAM Family खोलें और QR स्कैन करें या 6 अंकों का कोड डालें।',generateCode:'नया कोड बनाएं',openDashboard:'परिवार डैशबोर्ड खोलें',testJoin:'इस डिवाइस पर जुड़ने का प्रवाह जांचें',privateInvite:'निजी आमंत्रण • 10 मिनट में समाप्त',previewCode:'डेमो कोड • क्लाउड अभी जुड़ा नहीं है',expiresIn:'समाप्ति'},
  ja:{tagline:'家族の安全。いつでもつながる。',welcomeKicker:'家族の安全を、新しく',welcomeTitle:'干渉しすぎず、ずっと近くに。',welcomeSubtitle:'プライベートな家族位置情報、SOS、安全な場所、透明性のあるセーフティオーディオ。すべて同意と明確な操作を中心に設計。',parentRole:'保護者です',parentRoleSub:'プライベートな家族サークルを作成・管理します。',joinRole:'家族に参加します',joinRoleSub:'保護者から受け取った6桁のコードを入力します。',createFamily:'家族を作成',signIn:'サインイン',exploreDemo:'インタラクティブデモを見る',privacyFirst:'プライバシー優先',privacyFirstSub:'承認された家族だけがサークルにアクセスできます。',transparent:'透明性のある見守り',transparentSub:'位置情報やマイクの使用は家族メンバーの端末で隠されません。',global:'世界向けに設計',globalSub:'ヘブライ語・アラビア語のRTLを含む12言語で提供。',selectLanguage:'言語を選択',languageSubtitle:'希望する言語を選択してください。いつでも変更できます。',parentAccount:'保護者アカウント',createCircle:'家族サークルを作成',createCircleSub:'家族は初期設定で非公開です。招待した人だけが参加できます。',yourName:'あなたの名前',familyName:'家族名',email:'メール',password:'パスワード',passwordMin:'10文字以上',createNewFamily:'新しい家族を作成',welcomeBack:'おかえりなさい',signinTitle:'家族にサインイン',signinSub:'家族サークルは非公開で、通信中は暗号化されます。',joinSetup:'家族メンバー設定',joinTitle:'プライベートな家族サークルに参加',joinSub:'保護者から6桁のコードを受け取ります。ペアリングは見守りを隠したり、端末のプライバシー設定を回避したりしません。',inviteCode:'招待コード',memberName:'あなたの名前',joinFamily:'家族に参加',locationChoice:'位置情報はあなたが選択',locationChoiceSub:'AGAMは位置共有の前に許可を求め、必要なシステム表示を常に見える状態にします。',audioVisible:'セーフティオーディオは表示されます',audioVisibleSub:'マイク使用中は家族メンバーの端末で必ず表示されます。',addMember:'家族メンバーを追加',pairTitle:'1分以内でペアリング',pairSub:'もう一方の端末でAGAM Familyを開き、QRを読み取るか6桁コードを入力します。',generateCode:'新しいコードを生成',openDashboard:'家族ダッシュボードを開く',testJoin:'この端末で参加フローをテスト',privateInvite:'プライベート招待 • 10分で期限切れ',previewCode:'デモコード • クラウド未接続',expiresIn:'期限'},
  ko:{tagline:'가족 안전. 언제나 연결.',welcomeKicker:'새롭게 설계한 가족 안전',welcomeTitle:'부담스럽지 않게 가까이 지내세요.',welcomeSubtitle:'비공개 가족 위치, SOS, 안전 장소, 투명한 세이프티 오디오 — 동의와 명확한 제어를 중심으로 설계했습니다.',parentRole:'부모 / 보호자입니다',parentRoleSub:'비공개 가족 서클을 만들고 관리합니다.',joinRole:'가족에 참여합니다',joinRoleSub:'부모 또는 보호자에게 받은 6자리 코드를 입력하세요.',createFamily:'가족 만들기',signIn:'로그인',exploreDemo:'인터랙티브 데모 보기',privacyFirst:'개인정보 우선',privacyFirstSub:'승인된 가족만 서클에 접근할 수 있습니다.',transparent:'투명한 모니터링',transparentSub:'위치와 마이크 사용은 가족 구성원의 기기에서 절대 숨겨지지 않습니다.',global:'전 세계를 위해 설계',globalSub:'히브리어와 아랍어 RTL을 포함한 12개 출시 언어.',selectLanguage:'언어 선택',languageSubtitle:'선호 언어를 선택하세요. 언제든 변경할 수 있습니다.',parentAccount:'보호자 계정',createCircle:'가족 서클 만들기',createCircleSub:'가족은 기본적으로 비공개입니다. 초대한 사람만 참여할 수 있습니다.',yourName:'이름',familyName:'가족 이름',email:'이메일',password:'비밀번호',passwordMin:'10자 이상',createNewFamily:'새 가족 만들기',welcomeBack:'다시 오신 것을 환영합니다',signinTitle:'가족에 로그인',signinSub:'가족 서클은 비공개이며 전송 중 암호화됩니다.',joinSetup:'가족 구성원 설정',joinTitle:'비공개 가족 서클에 참여',joinSub:'부모 또는 보호자가 6자리 코드를 제공합니다. 페어링은 모니터링을 숨기거나 휴대폰 개인정보 설정을 우회하지 않습니다.',inviteCode:'초대 코드',memberName:'이름',joinFamily:'가족 참여',locationChoice:'위치 공유는 선택입니다',locationChoiceSub:'AGAM은 위치 공유 전에 권한을 요청하고 필요한 시스템 표시를 계속 보여줍니다.',audioVisible:'세이프티 오디오가 표시됩니다',audioVisibleSub:'마이크 세션은 가족 구성원의 기기에서 절대 숨겨지지 않습니다.',addMember:'가족 구성원 추가',pairTitle:'1분 안에 페어링',pairSub:'다른 기기에서 AGAM Family를 열고 QR을 스캔하거나 6자리 코드를 입력하세요.',generateCode:'새 코드 생성',openDashboard:'가족 대시보드 열기',testJoin:'이 기기에서 참여 흐름 테스트',privateInvite:'비공개 초대 • 10분 후 만료',previewCode:'데모 코드 • 클라우드 미연결',expiresIn:'만료'},
};

const KEY = 'agam.locale';
const supported = new Set(localeOptions.map(x=>x.code));
function deviceLocale(): LocaleCode {
  const raw = String(getLocales()[0]?.languageCode || 'en').toLowerCase();
  return supported.has(raw as LocaleCode) ? raw as LocaleCode : 'en';
}
async function loadSaved(): Promise<LocaleCode|null> {
  if (Platform.OS === 'web') return typeof window === 'undefined' ? null : (window.localStorage.getItem(KEY) as LocaleCode|null);
  return SecureStore.getItemAsync(KEY) as Promise<LocaleCode|null>;
}
async function persist(code:LocaleCode) {
  if (Platform.OS === 'web') { if (typeof window !== 'undefined') window.localStorage.setItem(KEY,code); return; }
  await SecureStore.setItemAsync(KEY,code,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY});
}

type LocaleContextValue = { locale:LocaleCode; isRTL:boolean; t:(key:TranslationKey)=>string; setLocale:(code:LocaleCode)=>Promise<void> };
const LocaleContext = createContext<LocaleContextValue>({locale:'en',isRTL:false,t:(key)=>en[key],setLocale:async()=>{}});

export function LocaleProvider({children}:{children:React.ReactNode}) {
  const [locale,setLocaleState] = useState<LocaleCode>(deviceLocale());
  useEffect(()=>{ loadSaved().then(saved=>{ if(saved && supported.has(saved)) setLocaleState(saved); }).catch(()=>{}); },[]);
  const value = useMemo<LocaleContextValue>(()=>({
    locale,
    isRTL: locale==='he'||locale==='ar',
    t:(key)=>resources[locale]?.[key] || en[key],
    setLocale:async(code)=>{ setLocaleState(code); await persist(code); },
  }),[locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useLocale(){ return useContext(LocaleContext); }
